In [2]:
import numpy as np
from Board import Board

In [2]:
board = Board(
    grid=np.array(
        [
            [1,2,0,2],
            [0,2,0,2],
            [1,0,0,0],
            [1,2,1,1]
        ]
    )
)
print(board)

[[1 2 0 2]
 [0 2 0 2]
 [1 0 0 0]
 [1 2 1 1]]


In [5]:
# main structure:

board = Board()
while not board.game_over:
    print(board)
    print(board.possible_moves)
    move = input("Move:" )
    board.move(move)
    board.add_2()
    board.check_possible_moves()
    board.is_game_over()

[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
['down', 'left', 'right']
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 2]]
['up', 'left', 'right']
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 0]
 [4 0 0 0]]
['up', 'down', 'left', 'right']
[[4 0 2 0]
 [0 0 0 0]
 [2 0 0 0]
 [0 0 0 0]]
['up', 'down', 'left', 'right']
[[4 0 2 0]
 [2 0 2 0]
 [0 0 0 0]
 [0 0 0 0]]
['up', 'down', 'left', 'right']
[[4 2 0 0]
 [4 0 0 2]
 [0 0 0 0]
 [0 0 0 0]]
['up', 'down', 'left', 'right']


Exception: Movement  is not allowed, try with: ['up', 'down', 'left', 'right']

In [3]:
print(board)
print("Left:")
print(board.move_left())

[[1 2 0 2]
 [0 2 0 2]
 [1 0 0 0]
 [1 2 1 1]]
Left:
[[1 4 0 0]
 [4 0 0 0]
 [1 0 0 0]
 [1 2 2 0]]


In [4]:
print(board)
print("Right:")
print(board.move_right())

[[1 2 0 2]
 [0 2 0 2]
 [1 0 0 0]
 [1 2 1 1]]
Right:
[[0 0 1 4]
 [0 0 0 4]
 [0 0 0 1]
 [0 1 2 2]]


In [5]:
print(board)
print("Up:")
print(board.move_up())

[[1 2 0 2]
 [0 2 0 2]
 [1 0 0 0]
 [1 2 1 1]]
Up:
[[2 4 1 4]
 [1 2 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
print(board)
print("Down:")
print(board.move_down())

[[1 2 0 2]
 [0 2 0 2]
 [1 0 0 0]
 [1 2 1 1]]
Down:
[[0 0 0 0]
 [0 0 0 0]
 [1 2 0 4]
 [2 4 1 1]]
