In [2]:
import numpy as np

In [45]:
def left_slide(v):
    N = len(v)
    # Remove zeros
    v_z = v[v!=0]
    # Join between equal numbers
    n = len(v_z)
    for i in range(n-1):
        if v_z[i]==v_z[i+1]:
            v_z[i] *= 2
            v_z[i+1] = 0
    # Remove zeros
    v_z = v_z[v_z!=0]
    m = len(v_z)
    # Padding
    return np.pad(v_z, (0, N-m))

In [5]:
def right_slide(v):
    N = len(v)
    # Remove zeros
    v_z = v[v!=0]
    # Join between equal numbers
    n = len(v_z)
    for i in range(n-1, 0, -1):
        if v_z[i]==v_z[i-1]:
            v_z[i] *= 2
            v_z[i-1] = 0
    # Remove zeros
    v_z = v_z[v_z!=0]
    m = len(v_z)
    # Padding
    return np.pad(v_z, (N-m, 0))

In [6]:
right_slide(
    np.array(
        [1, 2, 1, 1]
    )
)

array([0, 1, 2, 2])

In [48]:
v = np.array([
    0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 3, 1, 0, 0, 0, 0, 1, 1, 2, 2
])
N = len(v)
print(v)

v_z = v[v!=0]
print(v_z)

n = len(v_z)
for i in range(n-1):
    if v_z[i]==v_z[i+1]:
        v_z[i] *= 2
        v_z[i+1] = 0
print(v_z)

v_zz = v_z[v_z!=0]
print(v_zz)

m = len(v_zz)
print(np.pad(v_zz, (0, N-m)))

[0 1 1 1 1 1 2 1 2 2 2 3 1 0 0 0 0 1 1 2 2]
[1 1 1 1 1 2 1 2 2 2 3 1 1 1 2 2]
[2 0 2 0 1 2 1 4 0 2 3 2 0 1 4 0]
[2 2 1 2 1 4 2 3 2 1 4]
[2 2 1 2 1 4 2 3 2 1 4 0 0 0 0 0 0 0 0 0 0]


In [47]:
print(v)
N = len(v)
# Remove zeros
v_z = v[v!=0]
print(v_z)
# Join between similar numbers
n = len(v_z)
for i in range(n-1, 0, -1):
    if v_z[i]==v_z[i-1]:
        v_z[i-1] *= 2
        v_z[i] = 0
# Remove zeros
v_z = v_z[v_z!=0]
print(v_z)
m = len(v_z)
# Padding
print(np.pad(v_z, (N-m, 0)))

[0 1 1 1 1 1 2 1 2 2 2 3 1 0 0 0 0 1 1 2 2]
[1 1 1 1 1 2 1 2 2 2 3 1 1 1 2 2]
[1 2 2 2 1 2 4 3 1 2 4]
[0 0 0 0 0 0 0 0 0 0 1 2 2 2 1 2 4 3 1 2 4]


In [49]:
v = np.array([
    0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 3, 1, 0, 0, 0, 0, 1, 1, 2, 2
])
print(v)
print(left_slide(v))
print(right_slide(v))

[0 1 1 1 1 1 2 1 2 2 2 3 1 0 0 0 0 1 1 2 2]
[2 2 1 2 1 4 2 3 2 1 4 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 2 2 2 1 2 4 3 1 2 4]


In [36]:
for i in range(5, 0, -1):
    print(i)

5
4
3
2
1


In [50]:
a = np.arange(4*4).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
for u in range(4):
    print(a[u, :])

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [53]:
a[u, :]

array([12, 13, 14, 15])

In [54]:
a[:, u]

array([ 3,  7, 11, 15])